name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # Temporarily removed paths filter for debugging
    # paths:
    #   - "**/*.py"
    #   - "tests/**/*"
    #   - "requirements*.txt"
    #   - "pyproject.toml"
    #   - "CLAUDE.md"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
      checks: write
      actions: read
      statuses: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi

      - name: Debug PR context
        run: |
          echo "PR Number: ${{ github.event.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event Action: ${{ github.event.action }}"
          
      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@main
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Simplified configuration for reliable comment posting
          direct_prompt: |
            Please review this pull request focusing on:
            
            ## Code Quality
            - Type hints and documentation
            - Error handling and security
            - Performance considerations
            - Test coverage and quality
            
            ## Architecture
            - Follows existing patterns
            - Proper integration with codebase
            - Maintainability and readability
            
            Please provide specific feedback and suggestions for improvement.
            If you find any issues, please clearly explain them and suggest solutions.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          REPOSITORY: ${{ github.repository }}
          
          # Optional: Skip review for certain conditions
          # if: |
          #   !contains(github.event.pull_request.title, '[skip-review]') &&
          #   !contains(github.event.pull_request.title, '[WIP]')

